feat: FacilityForm component
Pensano-dev/aura-mobile-app pull request #31
Opened 2024-02-22 11:37 UTC by siqbal181

2024-02-26 19:36 UTC, siqbal181 commented
Back to draft.. playing around more!

2024-02-27 13:49 UTC, pablisch requested changes
Amazing! Great work, Sidra! 🙌🏼 Loving the modal. I'm going to have to look at that properly as I'm still a modal virgin. Everything looks great.

I asked for one tiny change as a comment but other than that:

- [ ] I get a console warning on Android that Arial is not a system font. It is only a warning but one we should probably get rid of.
- [ ] react-native-modal is not in package.json. I was getting a whole bunch of errors and took me a while to work it out. Probably worth warning when a PR requires an npm install but in this case it would not have helped. FYI, I have "react-native-modal": "^13.0.1", in my package.json now.

I don't know if you plan on continuing with the form, but in case you are, the endpoint is in main so if you align the facility names to those in the DB you should get a proper data response. There is also a baseUrl file in utils.

2024-02-27 13:49 UTC, pablisch commented on frontend/src/components/FacilityForm/FacilityForm.js
> +  const exampleList = [
A really small thing but can this be moved to the top outside the component function so that it only runs once since its value will never change.

2024-02-27 13:51 UTC, pablisch commented
This was the warning I got ![Screenshot 2024-02-27 at 13 38 20](https://github.com/Pensano-dev/aura-mobile-app/assets/19639889/7e9d4e04-7883-49ab-bef9-bc7fa4cec249)

2024-02-27 13:53 UTC, pablisch commented
Oh, and no conflict expected but please pull main into your branch.

2024-03-02 13:02 UTC, siqbal181 commented
@pablisch Thanks for the comments! have resolved now and noted the npm install required (I'll remember for others!)

Conflicts with main resolved

2024-03-02 14:10 UTC, pablisch approved these changes
This is great, Sidra. There is just one tiny issue which I am really happy if you want to leave for now so I am approving it and leaving the change up to you or not. On Android, the refresh icon has a grey box around it when it load. It goes away as soon as you do anything. I can't see anything that I understand would cause this because I can't even see anything applying any style to the icon.

For some reason, react-native-modal was still not in package.json., nor is it there on GitHub in your branch. It worked for me having installed it before but when I ran npm install it actually removed it and the app crashed which surprised me. Just letting you know in case you have it locally in which case your package.json is not being pushed which we should look into.

You mentioned that you wanted to do some backend stuff. The current endpoint is already quite interesting but will need filtering cafes that are currently open which should be done in the query rather than to the data if you fancy something fun in a documentation headache kind of way.

2024-03-02 14:11 UTC, pablisch commented
In case you don't see what I see, here is the grey box I mentioned...
![Screenshot 2024-03-02 at 13 42 10](https://github.com/Pensano-dev/aura-mobile-app/assets/19639889/ccad216f-a2ed-4ae8-937e-83cc959f489e)

2024-03-02 15:43 UTC, pablisch commented
Happy to review it and approve it with the tiny Android fix on another ticket. I think visibility and regular integration is much more important than than perfect feature merges.

2024-03-02 16:03 UTC, siqbal181 commented
> Happy to review it and approve it with the tiny Android fix on another ticket. I think visibility and regular integration is much more important than than perfect feature merges. Up to you... let me know either way.

Agree!!

2024-03-02 17:35 UTC, pablisch approved these changes
Looking forward to seeing this in main! Well done, Sidra. Let us know if you want to carry on with this or tackle something else.

2024-03-02 19:25 UTC, merged